before_commands:
  - 'git submodule update --init --recursive'
filter:
  excluded_paths:
    - 'lib/pkp/lib/*'
    - 'tests/*'
    - 'plugins/generic/externalFeed/simplepie/*'
tools:
  php_sim:
    enabled: true
    min_mass: 16
  php_pdepend:
    enabled: true
    suffixes:
      - php
  php_analyzer:
    enabled: true
    extensions:
      - php
  php_changetracking:
    enabled: true
    bug_patterns:
      - '\bfix(?:es|ed)?\b'
    feature_patterns:
      - '\badd(?:s|ed)?\b'
      - '\bimplement(?:s|ed)?\b'
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
