INSERT INTO `filters` 
VALUES
(1,0,'CrossRef','lib.pkp.classes.citation.lookup.crossref.CrossrefNlmCitationSchemaFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(2,0,'PubMed','lib.pkp.classes.citation.lookup.pubmed.PubmedNlmCitationSchemaFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(3,0,'WorldCat','lib.pkp.classes.citation.lookup.worldcat.WorldcatNlmCitationSchemaFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(4,0,'FreeCite','lib.pkp.classes.citation.parser.freecite.FreeciteRawCitationNlmCitationSchemaFilter','primitive::string','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(5,0,'ParaCite','lib.pkp.classes.citation.parser.paracite.ParaciteRawCitationNlmCitationSchemaFilter','primitive::string','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(6,0,'ParsCit','lib.pkp.classes.citation.parser.parscit.ParscitRawCitationNlmCitationSchemaFilter','primitive::string','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(7,0,'RegEx','lib.pkp.classes.citation.parser.regex.RegexRawCitationNlmCitationSchemaFilter','primitive::string','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(8,0,'ABNT Citation Output','lib.pkp.classes.citation.output.abnt.NlmCitationSchemaAbntFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','primitive::string',0,0,0),
(9,0,'ABNT Citation Output','lib.pkp.classes.citation.output.PlainTextReferencesListFilter','class::lib.pkp.classes.submission.Submission','class::lib.pkp.classes.citation.PlainTextReferencesList',0,0,0),
(10,0,'APA Citation Output','lib.pkp.classes.citation.output.apa.NlmCitationSchemaApaFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','primitive::string',0,0,0),
(11,0,'APA Citation Output','lib.pkp.classes.citation.output.PlainTextReferencesListFilter','class::lib.pkp.classes.submission.Submission','class::lib.pkp.classes.citation.PlainTextReferencesList',0,0,0),
(12,0,'MLA Citation Output','lib.pkp.classes.citation.output.mla.NlmCitationSchemaMlaFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','primitive::string',0,0,0),
(13,0,'MLA Citation Output','lib.pkp.classes.citation.output.PlainTextReferencesListFilter','class::lib.pkp.classes.submission.Submission','class::lib.pkp.classes.citation.PlainTextReferencesList',0,0,0),
(14,0,'Vancouver Citation Output','lib.pkp.classes.citation.output.vancouver.NlmCitationSchemaVancouverFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','primitive::string',0,0,0),
(15,0,'Vancouver Citation Output','lib.pkp.classes.citation.output.PlainTextReferencesListFilter','class::lib.pkp.classes.submission.Submission','class::lib.pkp.classes.citation.PlainTextReferencesList',0,0,0),
(16,0,'NLM Journal Publishing V3.0 ref-list','lib.pkp.classes.importexport.nlm.PKPSubmissionNlmXmlFilter','class::lib.pkp.classes.submission.Submission','xml::*',0,0,0),(17,0,'ISBNdb','lib.pkp.classes.filter.GenericSequencerFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',1,0,0),
(18,0,'ISBNdb (from NLM)','lib.pkp.classes.citation.lookup.isbndb.IsbndbNlmCitationSchemaIsbnFilter','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)','primitive::string',0,17,1),(19,0,'ISBNdb','lib.pkp.classes.citation.lookup.isbndb.IsbndbIsbnNlmCitationSchemaFilter','primitive::string','metadata::lib.pkp.classes.metadata.nlm.NlmCitationSchema(CITATION)',0,17,2),
(20,0,'NLM Journal Publishing V2.3 ref-list','lib.pkp.classes.filter.GenericSequencerFilter','class::lib.pkp.classes.submission.Submission','xml::*',0,0,0),
(21,0,'NLM Journal Publishing V3.0 ref-list','lib.pkp.classes.importexport.nlm.PKPSubmissionNlmXmlFilter','class::lib.pkp.classes.submission.Submission','xml::*',0,20,1),
(22,0,'NLM 3.0 to 2.3 ref-list downgrade','lib.pkp.classes.xslt.XSLTransformationFilter','xml::*','xml::*',0,20,2);

INSERT INTO `filter_settings` VALUES
(1,'','phpVersionMin','5.0.0','string'),
(2,'','phpVersionMin','5.0.0','string'),
(3,'','phpVersionMin','5.0.0','string'),
(4,'','phpVersionMin','5.0.0','string'),
(5,'','citationModule','Standard','string'),
(5,'','phpVersionMin','5.0.0','string'),
(6,'','phpVersionMin','5.0.0','string'),
(7,'','phpVersionMin','5.0.0','string'),
(9,'','citationOutputFilterName','lib.pkp.classes.citation.output.abnt.NlmCitationSchemaAbntFilter','string'),
(9,'','ordering','2','int'),
(11,'','citationOutputFilterName','lib.pkp.classes.citation.output.apa.NlmCitationSchemaApaFilter','string'),
(11,'','ordering','2','int'),
(13,'','citationOutputFilterName','lib.pkp.classes.citation.output.mla.NlmCitationSchemaMlaFilter','string'),
(13,'','ordering','2','int'),
(15,'','citationOutputFilterName','lib.pkp.classes.citation.output.vancouver.NlmCitationSchemaVancouverFilter','string'),
(15,'','ordering','1','int'),
(17,'','settingsMapping','a:2:{s:6:\"apiKey\";a:2:{i:0;s:11:\"seq1_apiKey\";i:1;s:11:\"seq2_apiKey\";}s:10:\"isOptional\";a:2:{i:0;s:15:\"seq1_isOptional\";i:1;s:15:\"seq2_isOptional\";}}','object'),(18,'','phpVersionMin','5.0.0','string'),
(19,'','phpVersionMin','5.0.0','string'),
(22,'','xsl','lib/pkp/classes/importexport/nlm/nlm-ref-list-30-to-23.xsl','string'),
(22,'','xslType','2','int');
