OJS 2.4.6 Release Notes
GIT tag: ojs-2_4_6-0
Release date: March 17, 2015
================================

Note: While we transition our issue management system from Bugzilla
(http://pkp.sfu.ca/bugzilla) to Github Issues
(http://www.github.com/pkp/pkp-lib/issues), this list will contain a mixture
of IDs from both systems. Bugzilla entries will be prefixed with "bz" and
Github issues will be prefixed with "i".

New Features
------------
	#bz8085# Make OJS more SPF-compatible in email sending
	#bz8927# Add PDF.js-based PDF viewer
	#bz8966# Add support for no-reply email sender address
	#bz9036# Improve body ID consistency for theming
	#bz9051# Add ORCiD field to QuickSubmit plugin
	#i277#: CustomBlockManager-PlugIn localised

Bug Fixes
---------
	#bz6625# Add DOI year cutoff OR Crossref XML year cutoff
	#bz7846# Tracking: OJS 2.4.x de_DE (German) locale fixes
	#bz8356# Enabling announcements pushes 'about' menu item onto new line
	#bz8747# Fatal error: Call to a member function getId() on a non-object
	#bz8777# Dataverse plugin: refactor redundant code in methods to create, update studies
	#bz8859# Improve copyright affixing behavior on upgrade
	#bz8898# Wrong "In submission" and "In editing" count in section editor's User Home
	#bz8913# Custom Theme plugin raises fatal error in Site usage
	#bz8917# usageStats FileLoader reports error status due to unset return
	#bz8920# Password fields should not have a maximum length
	#bz8921# Some users can't login after upgrade to OJS 2.4.5
	#bz8923# Call to undefined method SectionEditorSubmission::getDatePublished() in QuickSubmitForm
	#bz8926# Duracloud plugin ships with .git directory
	#bz8931# Site user home is missing journal listings for users associated with no journals
	#bz8932# JavaScript error in user login template with implicit auth
	#bz8933# signInAsUser page presents incorrect link to All Enrolled Users
	#bz8934# Fix article publication date assignment on issue publish
	#bz8935# Can't get additive statistics metrics
	#bz8944# Reset Password Screen has typo
	#bz8948# Broken links for "submission review" and "password reset" in review remind email
	#bz8953# Add legacy constants used in citation assistant
	#bz8956# Use random password for Shib plugin
	#bz8957# Universal Analytics site id is wrapped in Smarty literal
	#bz8958# Usage Stats settings form handler contains unused/unset variables
	#bz8962# UsageStats COUNTER bots file not found
	#bz8964# Investigate/fix layout editor proofreading
	#bz8972# COUNTER report triggers PHP error
	#bz8979# Remove explicit SSLv3 configuration
	#bz8981# duplicate id authorBio on article landing pages when there is more than one author (xhtml violation)
	#bz8983# Remove whitespace from templates prior to header.tpl being invoked
	#bz8984# duplicate id="issue" on archives page makes page fail xhtml validation
	#bz8985# register page duplicate id="register" (xhtml violation)
	#bz8986# PublishedArticleDAO contains non-SQL quoting
	#bz8988# ojs search page xhtml violation (input elements are not self closed as they should be)
	#bz8989# Search page, Searchtips: <ul> nested within <p> (xhtml violation)
	#bz8990# setup step5 (5.6 journal layout): table where you assign blocks to sidebars or unselected - Not enough space to display the name of blocks.
	#bz8991# Update Dataverse dataset with citation when article published
	#bz8992# Overwrite files on the Dataverse side when updated in OJS
	#bz8997# Support new metadata fields added to Dataverse data deposit API
	#bz8999# Block plugin updates settings table several times for each pageload
	#bz9016# PKP PLN plugin can't reach staging server on upgraded OJS installations
	#bz9018# COUNTER report counts other file types downloads as pdf
	#bz9019# Improve marcxml generated by OAI
	#bz9020# Plugin installer/updater moves plugin lib folders to the PKP WAL
	#bz9022# Improve WebFeed plugin's license/rights metadata
	#bz9033# Setting type 'boolean' is too long (and non-standard); use 'bool'
	#bz9035# Remove hardcoded "&#187" bullets
	#bz9042# copyright_holder element is localized
	#bz9047# Can't access stats & report from journals in OJS Portals before the current year
	#bz9054# Exported User's XML differs from the expected ones for importation
	#bz9056# Fix CrossRef multilingual behavior
	#bz9057# Default usage stats loader regex can't read apache log files in combined format
	#i245#: Large log messages in the FileLoader can exceed PHP's memory_limit
	#i249#: Acron plugin can't process scheduled tasks xml file without a frequency defined
	#i253#: ReportPlugin::report() parameter implementation is inconsistent
	#i255#: Article without Section causes fatal error
	#i259#: Some article orderings may drop content from Table of Contents
	#i262#: Timed views report double total galleys view counts and skip it in the last report row
	#i263#: ALM plugin request stats takes to much time to answer
	#i265#: Hide "Online Submissions" section of About when user registration disabled
	#i267#: CrossRef export may refer to wrong journal path
	#i271#: Allow Dataverse plugin to connect via API token
	#i273#: Web feed plugin doesn't flag Atom subtitle content as HTML
	#i275#: HTML syntax errors in HTML help
	#i276#: SSL redirect ignores base_url[<journal_name>]
	#i280#: Problem when deleting a CustomBlock
	#i282#: Dataverse plugin: remove markup from dataset metadata
	#i283#: Dataverse plugin: remove Dataverse file entry from database when suppfile deleted
	#i284#: Dataverse plugin: check API response for deprecation warnings
	#i285#: Galley Public Identifiers
	#i286#: Dataverse plugin: publish Dataverses via API
	#i288#: Make author index respect TOC author omit flags
	#i289#: Make Google Viewer plugin protocol-relative
	#i299#: UsageStats Loader doesn't recognize server aliases
	#i301#: Plugin upgrade form broken after error
	#i305#: Enhancement for uploading metadata to DOAJ
	#i308#: Dataverse plugin: deaccessioning not supported in API v1.1
	#i309#: Authors receive duplicated emails when editors use "Send email" functionality
	#i311#: Review Upgrade script "minversion" attributes for recent entries
	#i313#: Refback truncates to 80 characters at edit
	#i317#: Certain locale files in Objects for Review plugin are labelled en_US
	#i325#: Editor email parameters in OFR plugin are incorrect
	#i335#: Missing geoLocationTool raises error
	#i337#: Xml web service fails when it shouldn't
	#i338#: Add send notification email hook
	#i339#: Remote galleys are not used for statistics
	#i340#: Articles from journals not intented for public display appear in search and browse author/title list
	#i351#: Update copyright dates for 2015
	#i352#: Make sure Acron plugin will not hit maximum execution time
	#i355#: Labeling EPUB galleys according to their mime type
	#i359#: Metrics region column doesn't store correctly all region values
	#i360#: Problem with announcement type setting/checking
	#i366#: Journal statistics from previous years not available if no object was published
	#i371#: "Sponsors" incorrect in Portugese translation
	#i392#: Extend session hash field in database
	#i404#: Improvements to CrossRef deposit
